config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "gunslingers#index"

  resources :gunslingers
  resources :badge_templates
  resources :recruits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
require 'credly_badge_service'

class Badge < ApplicationRecord
  belongs_to :gunslinger
  validates :badge_template_id, presence: true

  after_save :post_to_credly

  def issued_at
    self.created_at
  end

  def post_to_credly
    CredlyBadgeService::post_badge(
      gunslinger: gunslinger,
      badge_template_id: badge_template_id
    )
  end
end

app/models/gunslinger.rb
require 'credly_badge_service'

class Gunslinger < ApplicationRecord
  has_many :badges

  validates :first_name, :last_name, :email, presence: true

  def issued_badges
    CredlyBadgeService::get_badge(gunslinger: self)
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/badge_templates_controller.rb
require 'credly_badge_service'

class BadgeTemplatesController < ApplicationController
    def index
        badge_templates = CredlyBadgeService::get_badge_templates

        render 'index', locals: {
            badge_templates: badge_templates,
            gunslinger_name: params[:gunslinger_name]
        }
    end
end

app/controllers/gunslingers_controller.rb
require 'credly_badge_service'

class GunslingersController < ApplicationController
    def index
        gunslingers = Gunslinger.all
        render 'index', locals: {gunslingers: gunslingers}
    end

    def new
        first_name, last_name = params[:gunslinger_name].split(' ', 2)
        last_name ||= '[No last name]'
        render 'new', locals: {
            first_name: first_name,
            last_name: last_name,
            badge_template: params[:badge_template]
        }
    end

    def create
        gunslinger_params = params.permit(
            :first_name,
            :last_name,
            :email
        )

        badge_params = params.permit(
            :badge_template_id
        )

        gunslinger = Gunslinger.new(gunslinger_params) 

        if gunslinger.save
            badge = Badge.create(gunslinger: gunslinger, badge_template_id: badge_params[:badge_template_id])
            flash[:notice] = 'Congratulations, you\'ve recruited a gunslinger'
            redirect_to gunslingers_path
        else
            flash[:notice] = gunslinger.errors
        end 
    end
end

app/controllers/recruits_controller.rb
require 'marvel_characters_service'

class RecruitsController < ApplicationController
    def index
        recruits = MarvelCharactersService::get_characters
        render 'index', locals: {recruits: recruits}
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gunslingers_helper.rb
require 'credly_badge_service'

module GunslingersHelper
    def badge_image_url(gunslinger)
        return if gunslinger.badges.empty?

        badge_template ||= CredlyBadgeService.get_badge_template(badge: gunslinger.badges.first)
        badge_template['image_url']
    end

    def default_email_address(first_name, last_name)
        "#{first_name.downcase}.#{last_name&.split&.first&.downcase}@example.com"
    end
end

app/views/badge_templates/index.html.erb
<h1>Select a badge</h1>
<% badge_templates.each do |badge_template| %>
    <%= image_tag badge_template['image_url'], class: 'badge-image large' %>
    <%= link_to badge_template['name'], new_gunslinger_path(badge_template: badge_template, gunslinger_name: gunslinger_name), class: "button-link" %>
<% end %>

app/views/gunslingers/index.html.erb
<h1>Gunslingers</h1>
    <%= link_to 'Recruit a new gunslinger', recruits_path, class: 'button-link call-to-action' %>
<ul class="gunslingers-list">
    <% gunslingers.each do |gunslinger| %>
        <li class="gunslingers-list-item">
            <% unless badge_image_url(gunslinger).nil? %>
                <%= image_tag badge_image_url(gunslinger), class: "badge-image small"%>
            <% end %>
            <h2>
                <%= "#{gunslinger.first_name} #{gunslinger.last_name}" %>
            </h2>
        </li>
    <% end %>
</ul>

app/views/gunslingers/new.html.erb
<h1> Submit info for badging <h1>
<%= form_with model: @gunslinger, url: '/gunslingers' do |form| %>
    <%= form.label :first_name, "First name", class: 'form-label' %>
    <%= form.text_field :first_name, value: first_name %>
    <%= form.label :last_name, "Last name", class: 'form-label' %>
    <%= form.text_field :last_name, value: last_name %>
    <%= form.label :email, "Email", class: 'form-label' %>
    <%= form.text_field :email, value: default_email_address(first_name, last_name) %>
    <%= form.hidden_field :badge_template_id, value: badge_template['id'] %>
    <%= form.submit %>
<% end %>

app/views/layouts/_primary_navigation.html.erb
<nav role="navigation", aria-label="Main Navigation">
    <% if user_signed_in? %>
        <%= link_to 'Log out', destroy_user_session_path, { method: :DELETE, class: "button-link log-out" } %>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gunslingerer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= render 'layouts/primary_navigation' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recruits/index.html.erb
<h1>Recruits</h1>
<ul class="recruits-list">
    <% recruits.each do |recruit| %>
        <li class="recruits-list-item">
            <h2><%= link_to recruit['name'], badge_templates_path(gunslinger_name: recruit['name']) %></h2>
            <p><%= recruit['description']%></p>
        </li>
    <% end %>
</ul>